apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim
  labels:
    app: postgresql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-gp2
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
    tier: database
spec:
  selector:
    matchLabels:
      app: postgresql
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
        tier: database
    spec:
      containers:
        - image: postgres:15
          args:
            - "--ignore-db-dir=lost+found"
          name: postgresql
          env:
            - name: POSTGRES_ROOT_PASSWORD
              value: "12345"
            - name: POSTGRES_DB
              value: "questiondb"
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: postgresql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql
    tier: database
  clusterIP: None
